const Data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim shirt',
            slug: 'nike-slim-shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 3,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            _id: '2',
            name: 'Adidas Fit shirt',
            slug: 'adidas-fit-shirt',
            image:'/images/p2.jpg',
            price: 250,
            countInStock: 6,
            brand: 'Nike',
            rating: 2,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Adidas fit Pant',
            slug: 'adidas-fit-pant',
            category: 'Pants',
            image:'/images/p3.jpg',
            price: 25,
            countInStock: 15,
            brand:'Nike',
            rating: 5,
            numReviews: 14,
            description:'high quality pants',
        },
        {
            _id: '4',
            name: 'Nike slim pant',
            slug: 'nike-slim-pant',
            category: 'Pants',
            image:'/images/p4.jpg',
            price: 25,
            countInStock: 15,
            brand:'Nike',
            rating: 4,
            numReviews: 14,
            description:'high quality pants',
        },
    ],
};

export default Data;